export { classifyTile, type HydrologyClassification } from './classify'
export {
	AUTO_GPU_MIN_TILES,
	canUseWebGpuFields,
	createFieldGenerationShaderSource,
	disposeGpuFieldRuntime,
	FIELD_RESULT_STRIDE,
	FIELD_SHADER_ENTRYPOINT,
	generateFields,
	generateFieldsAsync,
	generateFieldsGpu,
	generateFieldsWasm,
	generateSectorFieldsWasm,
	generateTileField,
	generateTileFieldAsync,
	generateTileFieldGpu,
	generateTileFieldWasm,
	isGpuFieldRuntimeReady,
	isWasmFieldGenerationAvailable,
	type PackedFieldRequest,
	type PackedFieldResult,
	packFieldRequest,
	resolveAsyncFieldGenerationBackend,
	resolveFieldGenerationBackend,
	resolveSyncFieldGenerationBackend,
	unpackFieldResult,
	type WasmSectorCoord,
	type WasmSectorFieldBatch,
	warmGpuFieldRuntime,
} from './fields'
export { generateFieldsCpu, generateTileFieldCpu } from './fields/cpu'
export {
	applyTileOverrides,
	createSnapshot,
	DEFAULT_SECTOR_HYDROLOGY_PADDING,
	edgeKey,
	type GenerateHydratedRegionOptions,
	type GenerateHydratedRegionWithMetricsResult,
	type GenerateOptions,
	type GenerateSectorRegionOptions,
	generate,
	generateAsync,
	generateHydratedRegion,
	generateHydratedRegionAsync,
	generateHydratedRegionAsyncWithMetrics,
	generateHydratedRegionWithMetrics,
	generateRegion,
	generateRegionAsync,
	generateSectorRegionAsync,
	generateSectorRegionAsyncWithMetrics,
	generateTile,
	type MergeSnapshotResult,
	mergeSnapshotRegion,
	type PopulateSnapshotResult,
	populateSnapshot,
	populateSnapshotAsync,
	pruneSnapshot,
	type TerrainSectorCoord,
	type TileOverride,
} from './generate'
export * from './hex/index'
export { type HydrologyResult, isSpring, runHydrology, runHydrologyDetailed } from './hydrology'
export {
	DEFAULT_MACRO_HYDROLOGY_SECTOR_RADIUS,
	DEFAULT_MACRO_HYDROLOGY_SECTOR_STEP,
	DEFAULT_MACRO_HYDROLOGY_STEP,
	type GenerateMacroHydrologyOptions,
	generateMacroHydrologyWasm,
	type TerrainMacroHydrologySnapshot,
	type TerrainMacroRiverSegment,
	type TerrainMacroTile,
} from './macro-hydrology'
export { dumpNoiseProfile, fbm, PerlinNoise, resetNoiseProfile } from './noise'
export * from './types'
export {
	ensureWasmLoaded,
	getWasmModule,
	isWasmLoaded,
	loadWasmModule,
	wasmLoadReady,
} from './wasm-loader'
